app/Controllers/Http/ExplorerController.js
client/package.json
client/src/api.js
client/src/app.js
client/src/components/FileExplorer.vue
client/src/components/WindowSplitting.vue
client/src/pages/LoggedInLayout.vue
client/src/store.js
config/index.js
package.json
public/index.html
start/routes.js

- Fixed position in top-right
- Define width and fontSize in config file

Update right menu:

---

.env.example
.gitignore
README.md
app/Controllers/Http/ExplorerController.js
app/Middleware/AuthMiddleware.js
client/package.json
client/src/api.js
client/src/app.js
client/src/components/File.vue
client/src/components/FileExplorer.vue
client/src/components/WindowSplitting.vue
client/src/pages/LoggedInLayout.vue
client/src/socket.js
client/src/store.js
config/index.js
config/ui.js
logger.js
package.json
public/index.html
start/routes.js

- Requirement 1: Right side menu
- Requirement 2: Limit file per page
- Requirement 4: File names
- Requirement 5: Change delete
- Requirement 6: Logging user activities

Pagination

---

Dockerfile

Right now, the `svtrain` user inside the docker image had a little too few permissions (esp. on the `/data` dir). Reordered the commands to fix this, but in a way to not allow too many permissions.

Optimize user permissions in Dockerfile

---

app/Controllers/Http/FileController.js
client/src/components/File.vue
client/src/components/ShowImage.vue
client/src/utils/index.js
client/src/views/Login.vue
start/routes.js

Static images should not be available publicly, this PR makes them protected.

Put images behind auth

---

start/routes.js

Reverts com2u/SVTrain#82
Can we please clarify what's not working for you and not revert the changes? Images needs auth and this is not the right way to fix it.

Revert "+ Fix static load"

---

Dockerfile

Revert "[Draft do not merge to Master] Install TF2.6 and dependencies"

---

client/package.json
client/src/components/WSOption.vue
client/src/components/field/Index.vue
client/src/views/WorkSpace.vue

- Increase user friendliness to setup and change a workspace setting.
- Make the changes according to the mockup.
- The permission setting without the UI should still show the JSON editor.

update workspace settings UI

---

app/Controllers/Http/ExplorerController.js
client/src/views/Validate.vue
externalpath.json.example

Provide the following additional setting in an externalpath.json with the following settings:
- `GenerateAIReportURL`
- `LastReportURL`
Add two iframes into the Validate screen and show the related URLs

Integrate AI Report

---

app/Controllers/Http/ExplorerController.js
client/package.json
client/src/components/FileExplorer.vue
client/src/utils/api.js
client/src/utils/socket.js
client/yarn.lock

- Order by:
• Image notes
• Stars
- Filter
• Lables (List of Lables)
• Stars (1,2,3,4,5)
• Notes (yes, no)

Extend the filters in the file explorer

---

app/Controllers/Http/ExplorerController.js
app/Middleware/AuthMiddleware.js
client/src/components/Header.vue
client/src/components/WorkspaceFolder.vue
client/src/utils/api.js
client/src/views/WorkSpace.vue
package.json
yarn.lock

as of
[SVT-92865746-290722-1353-114.pdf](https://github.com/com2u/SVTrain/files/9230058/SVT-92865746-290722-1353-114.pdf)

Optimize loading time workspace list

---

app/Controllers/Http/ExplorerController.js
client/src/components/File.vue
client/src/components/FileExplorer.vue
client/src/components/StatisticPopup.vue
client/src/components/WSOption.vue
client/src/components/WorkspaceFolder.vue

bug 1) scales in changing contrast and brightness are wrong
bug 2) zoom function does not work 
bug 3) Confirm method does not work anymore
bug 4) Progress bar out of function
bug 5) amount of images shown does not match the settings file

fix bugs after implementing caching

---

client/src/components/WorkspaceFolder.vue

Show a process bar for each folder. To calculate the progress value per folder: Count the files in the folder "Unclassified" and all other folders as sorted. Calculate the progress as = sorted*100/(sorted+unsorted). When the user clicks the progress bar open the statistics page for this folder.
If progress bars are visible in sub folders, the percentages should be correct and not always show 100% or 0% for the "unclassified" folder (see example screenshot)

SWT-434 | Bugfix to calculate workspace progress bar

---

app/Controllers/Http/ExplorerController.js
client/src/components/FileExplorer.vue
client/src/components/WorkspaceFolder.vue
src/Statistic/index.js

EjectX confirm button does not work
EjectX Count shows "NaN" insted of 0

Bugfix: SWT-441 / SWT-442

---

app/Controllers/Http/ExplorerController.js
app/Middleware/AuthMiddleware.js
client/src/components/FileExplorer.vue
client/src/components/ShowFile.vue
client/src/components/ShowImage.vue
client/src/components/TFOption.vue
client/src/views/Test.vue
client/src/views/Train.vue
client/src/views/Validate.vue

- SWT-489 fixed
- SWT-482 fixed
- SWT-473 fixed
- SWT-509 fixed
- SWT-515 fixed
- not on Jira "I can't store workspace notes" fixed
- For SWT-491 (All images are shown instead of 20) is not a bug, the instance is just not updated, it is still on version 1.4.20-6866fdb please update to at least version 1.4.20-4b8ef1d and the bug will be fixed.

Bugfix/489 482 473 509 515 +fix notes bug 

---

ui/src/components/StatisticTable.vue

Removing the toggle button for autofit/scroll and exclude/all option.

removing the toggle button for autofit/scroll and exclude/all option

---

ui/src/components/StatisticTable.vue
ui/src/components/WorkspaceFolder.vue

Rename folders in label overview for the work space directory.

Swt 908 folder renaming

---

api/app/Controllers/Http/ExplorerController.js
ui/src/components/StatisticTable.vue

fixing the Confusion Matrix & labelling and coloring AI results

---

ui/src/components/TFOption.vue

SWT-1011 setting dialog for eject-x ai-report

---

ui/src/components/WorkspaceFolder.vue
ui/src/views/Validate.vue

SWT-868 setting the icons that is more relatable for the actions

---

ui/src/components/TFOption.vue

SWT-801 adding the dropdown for the epsilon parameter in the ai traning section

---

ui/src/components/WorkspaceFolder.vue
ui/src/views/Validate.vue

Revert "SWT-868 setting the icons that is more relatable for the actions"
